### ISSUE TITLE
Allow signing up with email

### ISSUE THREAD

**Issue by harabat** [curvenote/curvenote-dev#4]
Hope this is on the roadmap, as the current single option (google) is too restrictive. Github/Gitlab signup would also be a welcome option I think. 

Thanks!

**Comment by rowanc1** [comment]
Thanks - yes we have heard that a few times recently, thank you for raising it here! Sorry that you bounced there. :(

**Comment by harabat** [comment]
No worries! It's good to hear that you've been hearing feedback recently though, curvenote seems like a great tool on paper (looking forward to finding out in practice :)).

**Comment by rowanc1** [comment]
Thanks! Yeah - we are working hard on the features and forgot a bit about the front door. 😂

If you want to observe from a slack channel feel free to join our community slack here: https://slack.curvenote.dev/

I will leave this open and try to remember to close it when we fix it up: if you want to follow along to our bi-weekly progress:
https://eepurl.com/gSTYyv

(I am sure that I will mention non-google logins in there!)

**Comment by rowanc1** [comment]
Deployed today!

![image](https://user-images.githubusercontent.com/913249/111700763-7ab49f80-87ff-11eb-835b-8db17095ace8.png)

Thanks again @harabat for commenting here! :)
